version: '3.7'

services:

  host-ui:
    image: registry-pull.viamedis.fr/common/host-ui:${VERSION_BUILD}
    container_name: host-ui
    restart: unless-stopped
    ports:
      - "8030:8080"
    environment:
      #      ************ REMOTE APPs **********************************************************
      - REMOTE_LIB_UI=http://10.241.25.21:8038/remoteEntry.js
      - REMOTE_SHARED_LIB_UI=http://10.241.25.21:8039/remoteEntry.js
      - REMOTE_TPS_UI=http://10.241.25.21:8031/remoteEntry.js
      - REMOTE_HOSPI_UI=http://10.241.25.21:8032/remoteEntry.js
      - REMOTE_INTRAITABLES_UI=http://10.241.25.21:8037/remoteEntry.js
      - REMOTE_PAYEMENTS_UI=http://10.241.25.21:8033/remoteEntry.js
      - REMOTE_PS_UI=http://10.241.25.21:8034/remoteEntry.js
      - REMOTE_BENEF_UI=http://10.241.25.21:8035/remoteEntry.js
      - REMOTE_INDU_UI=http://10.241.25.21:8036/remoteEntry.js

      #      ************ API ***************************************************************
      - APIURL_ROC_SEL_IDB=http://10.241.25.21:8001/api/v1
      - APIURL_PS=http://10.241.25.21:8002/api/v1
      - APIURL_PAIEMENT_VIREMENT=http://10.241.25.21:8003/api/v1
      - APIURL_REFERENTIELS=http://10.241.25.21:8004/api/v1
      - APIURL_HOSPI_FACTURES=http://10.241.25.21:8005/api/v1
      - APIURL_BENEFICIAIRE=http://10.241.25.21:8007/api/v1
      - APIURL_INTEGRATION_FACTURE_INTRITABLES=http://10.241.25.21:8014/api/v1
      - APIURL_AGREGATOR=http://10.241.25.21:8015/api/v1
      - APIURL_TPS_FACTURES=http://10.241.25.21:8017/api/v1
      - APIURL_TP_AMC_SEL_IDB=http://10.241.25.21:8020/api/v1
      - APIURL_INDUS=http://10.241.25.21:8023/api/v1
      - APIURL_USER_MANAGEMENT=https://apim-dev-socle.azure-api.net/users-profiles-api/v1
