version: '3.6'

services:

  host-ui:
    image: registry-pull.viamedis.fr/common/host-ui:${VERSION_SNAPSHOT}
    container_name: host-ui
    restart: unless-stopped
    ports:
      - "8030:8080"
    environment:
#      ************ REMOTE APPs **********************************************************
      - REMOTE_LIB_UI=http://10.241.25.21:8038/remoteEntry.js
      - REMOTE_SHARED_LIB_UI=http://10.241.25.21:8039/remoteEntry.js
      - REMOTE_TPS=http://10.241.25.21:8031/remoteEntry.js
      - REMOTE_HOSPI=http://10.241.25.21:8032/remoteEntry.js
      - REMOTE_INTRAITABLES=http://10.241.25.21:8037/remoteEntry.js
      - REMOTE_PAYEMENTS=http://10.241.25.21:8033/remoteEntry.js
      - REMOTE_PS=http://10.241.25.21:8034/remoteEntry.js
      - REMOTE_BENEF=http://10.241.25.21:8035/remoteEntry.js
#      ************ API ***************************************************************
      - APIURL_BENEFICIAIRE=http://10.241.25.21:8007/api/v1
      - APIURL_CONFIGURATIONS=http://10.241.25.21:8015/api/v1
      - APIURL_DOWNLOAD_FACTURE=http://10.241.25.21:8015/api/v1
      - APIURL_DOWNLOAD_SEL_IDB=http://10.241.25.21:8015/api/v1
      - APIURL_ENTITIES=http://10.241.25.21:8031/api/entities
      - APIURL_FACTURES=http://10.241.25.21:8005/api/v1
      - APIURL_FLUX_FACTURES=http://10.241.25.21:8014/api/v1
      - APIURL_INTRAITABLES=http://10.241.25.21:8014/api/v1
      - APIURL_PAIEMENTS=http://10.241.25.21:8003/api/v1
      - APIURL_PS=http://10.241.25.21:8002/api/v1
      - APIURL_SEL_IDB=http://10.241.25.21:8001/api/v1
      - APIURL_FLUX_SEL_IDB=http://10.241.25.21:8001/api/v1
      - APIURL_VIREMENTS=http://10.241.25.21:8003/api/v1
      - APIURL_TPS_FACTURES=http://10.241.25.21:8017/api/v1
      - APIURL_TP_AMC_SEL_IDB=http://10.241.25.21:8020/api/v1
      - APIURL_REFS=http://10.241.25.21:8015/api/v1
      - APIURL_REFERENTIELS=http://10.241.25.21:8004/api/v1
