variables:
  PROJECT_NAME: host-ui
  PROJECT_GROUP: COMMON
  COMPOSE_NAME: HOST-UI
  DOCKER_IMAGE_NAME_FE: common/host-ui
  DOCKER_SERVICE_NAME_FE: host-ui
  DOCKER_DOCKERFILE_FE: Dockerfile
  VERSION: 0.3.6-SSO-1
  VERSION_SNAPSHOT: 0.3.6-SNAPSHOT

include:
  - project: devops/infrastructure/ci-library
    ref: '2.13.0'
    file:
      - pipelines/frontend.yml
      - components/env-definitions-azure-docker.yml

test-sonarqube-checks:
  allow_failure: true

test-owasp-dependency-check:
  allow_failure: true

