variables:
  PROJECT_NAME: host-ui
  PROJECT_GROUP: COMMON
  COMPOSE_NAME: HOST-UI
  DOCKER_IMAGE_NAME_FE: common/host-ui
  DOCKER_SERVICE_NAME_FE: host-ui
  DOCKER_DOCKERFILE_FE: Dockerfile
  NODE_IMAGE: node:20.10.0
  APPLICATION_VALUES_PATH: "frontend/host-ui.yaml"

include:
  - project: devops/infrastructure/ci-library
    ref: 'develop'
    file:
      - pipelines/frontend.yml
      - components/env-definitions-azure-docker.yml
