variables:
  PROJECT_NAME: host-ui
  PROJECT_LABEL: Host UI
  PROGECT_GROUP: COMMON
  COMPOSE_NAME: HOST-UI
  DOCKER_IMAGE_NAME_FE: common/host-ui
  DOCKER_SERVICE_NAME_FE: host-ui
  DOCKER_DOCKERFILE_FE: Dockerfile
  VERSION: 0.1.0
  VERSION_SNAPSHOT: 0.1.0-SNAPSHOT

include:
  - project: 'groupe-vdhm/infra/infrastructure'
    ref: gitlab-reusable-pipelines
    file: '/frontend/.gitlab-ci-latest.yml'
