module.exports = {
    clearMocks: true,
    collectCoverage: true,
    collectCoverageFrom: ["src/**/*.{js,jsx,mjs}"],
    coverageDirectory: "coverage",
    coverageReporters: ["json", "lcov"],
    moduleFileExtensions: ["js", "json", "jsx"],
    setupFiles: ["@testing-library/react/dont-cleanup-after-each"],
    testEnvironment: "jsdom",
    testEnvironmentOptions: { url: "http://localhost/" },
    snapshotResolver: "<rootDir>/jest/snapshotResolver.js",
    testMatch: ["**/__tests__/**/*.js?(x)", "**/?(*.)+(spec|test).js?(x)"],
    testPathIgnorePatterns: ["\\\\node_modules\\\\"],
    transformIgnorePatterns: ["<rootDir>/node_modules/"],
    verbose: false,
    setupFilesAfterEnv: ["<rootDir>/jest/jest.setup.js"],
    moduleNameMapper: {
        "lib_ui/react": "react",
        "lib_ui/react-dom": "react-dom",
        "lib_ui/react-router-dom": "react-router-dom",
        "lib_ui/reduxjs-toolkit": "@reduxjs/toolkit",
        "lib_ui/react-idle-timer": "react-idle-timer",
        "lib_ui/@azure-msal-react": "@azure/msal-react",
        "lib_ui/@azure-msal-browser": "@azure/msal-browser",
        "^.+\\.(css|style|less|sass|scss|png|jpg|ttf|woff|woff2|svg)$": "jest-transform-stub",
    },
    transform: {
        "^.+\\.jsx?$": "babel-jest",
        "^.+\\.js?$": "babel-jest",
        "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/jest/fileTransformer.js",
    },
};
