version: '3.6'

services:

  host-ui:
    image: registry-pull.viamedis.fr/common/host-ui:${VERSION_SNAPSHOT}
    container_name: host-ui
    restart: unless-stopped
    ports:
      - "8030:8080"
    environment:
#      ************ REMOTE APPs **********************************************************
      - REMOTE_LIB_UI=http://10.241.25.20:8038/remoteEntry.js
      - REMOTE_SHARED_LIB_UI=http://10.241.25.20:8039/remoteEntry.js
      - REMOTE_TPS_UI=http://10.241.25.20:8031/remoteEntry.js
      - REMOTE_HOSPI_UI=http://10.241.25.20:8032/remoteEntry.js
      - REMOTE_INTRAITABLES_UI=http://10.241.25.20:8037/remoteEntry.js
      - REMOTE_PAYEMENTS_UI=http://10.241.25.20:8033/remoteEntry.js
      - REMOTE_PS_UI=http://10.241.25.20:8034/remoteEntry.js
      - REMOTE_BENEF_UI=http://10.241.25.20:8035/remoteEntry.js
      - REMOTE_INDU_UI=https://10.241.25.20:8036/remoteEntry.js
#      ************ API ***************************************************************
      - APIURL_ROC_SEL_IDB=https://int-api.viamedis.net/roc-api/v1
      - APIURL_PS=https://int-api.viamedis.net/ps-api/v1
      - APIURL_PAIEMENT_VIREMENT=https://int-api.viamedis.net/paiement-api/v1
      - APIURL_REFERENTIELS=https://int-api.viamedis.net/referentiel-api/v1
      - APIURL_HOSPI_FACTURES=https://int-api.viamedis.net/hospi-facturation-api/v1
      - APIURL_BENEFICIAIRE=https://int-api.viamedis.net/droits-beneficiaire-api/v1
      - APIURL_INTEGRATION_FACTURE_INTRITABLES=https://int-api.viamedis.net/facturation-integration-api/v1
      - APIURL_AGREGATOR=https://int-api.viamedis.net/aggregator-api/v1
      - APIURL_TPS_FACTURES=https://int-api.viamedis.net/tps-facturation-internal-api/v1
      - APIURL_TP_AMC_SEL_IDB=https://int-api.viamedis.net/tp-amc-internal-api/v1
      - APIURL_USER_MANAGEMENT=https://10.241.25.10:8044/api/auth/v1

#      - APIURL_BENEFICIAIRE=http://10.241.25.20:8007/api/v1
#      - APIURL_CONFIGURATIONS=http://10.241.25.20:8015/api/v1
#      - APIURL_DOWNLOAD_FACTURE=http://10.241.25.20:8015/api/v1
#      - APIURL_DOWNLOAD_SEL_IDB=http://10.241.25.20:8015/api/v1
#      - APIURL_FACTURES=http://10.241.25.20:8005/api/v1
#      - APIURL_FLUX_FACTURES=http://10.241.25.20:8014/api/v1
#      - APIURL_INTRAITABLES=http://10.241.25.20:8014/api/v1
#      - APIURL_PAIEMENTS=http://10.241.25.20:8003/api/v1
#      - APIURL_PS=http://10.241.25.20:8002/api/v1
#      - APIURL_SEL_IDB=http://10.241.25.20:8001/api/v1
#      - APIURL_FLUX_SEL_IDB=http://10.241.25.20:8001/api/v1
#      - APIURL_VIREMENTS=http://10.241.25.20:8003/api/v1
#      - APIURL_TPS_FACTURES=http://10.241.25.20:8017/api/v1
#      - APIURL_TP_AMC_SEL_IDB=http://10.241.25.20:8020/api/v1
#      - APIURL_AGREGATOR=http://10.241.25.20:8015/api/v1
#      - APIURL_REFS=http://10.241.25.20:8015/api/v1
#      - APIURL_REFERENTIELS=http://10.241.25.20:8004/api/v1
