version: '3.1.9'

services:

  host-ui:
    image: registry-pull.viamedis.fr/common/host-ui:${VERSION_BUILD}
    container_name: host-ui
    restart: unless-stopped
    ports:
      - "8030:8080"
    environment:

      #      ************ REMOTE APPs **********************************************************
      - REMOTE_LIB_UI=http://10.241.25.20:8038/remoteEntry.js
      - REMOTE_SHARED_LIB_UI=http://10.241.25.20:8039/remoteEntry.js
      - REMOTE_TPS_UI=http://10.241.25.20:8031/remoteEntry.js
      - REMOTE_HOSPI_UI=http://10.241.25.20:8032/remoteEntry.js
      - REMOTE_INTRAITABLES_UI=http://10.241.25.20:8037/remoteEntry.js
      - REMOTE_PAYEMENTS_UI=http://10.241.25.20:8033/remoteEntry.js
      - REMOTE_PS_UI=http://10.241.25.20:8034/remoteEntry.js
      - REMOTE_BENEF_UI=http://10.241.25.20:8035/remoteEntry.js
      - REMOTE_INDU_UI=http://10.241.25.20:8036/remoteEntry.js
      - REMOTE_AUTH_UI=https://10.241.25.10:8040/remoteEntry.js

      #      ************ API ***************************************************************
      - APIURL_ROC_SEL_IDB=https://int-api.viamedis.net/roc-api/v1
      - APIURL_PS=https://int-api.viamedis.net/ps-api/v1
      - APIURL_PAIEMENT_VIREMENT=https://int-api.viamedis.net/paiement-api/v1
      - APIURL_REFERENTIELS=https://int-api.viamedis.net/referentiel-api/v1
      - APIURL_HOSPI_FACTURES=https://int-api.viamedis.net/hospi-facturation-api/v1
      - APIURL_BENEFICIAIRE=https://int-api.viamedis.net/droits-beneficiaire-api/v1
      - APIURL_INTEGRATION_FACTURE_INTRITABLES=https://int-api.viamedis.net/facturation-integration-api/v1
      - APIURL_AGREGATOR=https://int-api.viamedis.net/aggregator-api/v1
      - APIURL_TPS_FACTURES=https://int-api.viamedis.net/tps-facturation-api/v1
      - APIURL_TP_AMC_SEL_IDB=https://int-api.viamedis.net/tp-amc-api/v1
      - APIURL_INDUS=https://int-api.viamedis.net/indu-api/v1
      - APIURL_USER_MANAGEMENT=https://apim-dev-socle.azure-api.net/users-profiles-api/v1

      #      ***************************** AUTH *****************************************************
      # ...

