#############################
#    REUSABLE COMPONENTS    #
#############################

.build_on_develop: &build_on_develop
  only:
    - develop
  variables:
    VERSION_BUILD: $VERSION_SNAPSHOT

.deploy_on_dev: &deploy_on_dev
  only:
    - develop
  variables:
    ID_RSA: $ID_RSA_DEV
    SERVER_USER: $SERVER_USER_DEV
    SERVER_IP: $SERVER_IP_DEV
    ENV: "dev"

########################
#    SNAPSHOT STEPS    #
########################

snapshot-npm-dev:
  extends: .build
  stage: snapshot
  when: on_success
  <<: *build_on_develop

snapshot-docker-dev:
  extends: .publish
  stage: snapshot2
  when: on_success
  <<: *build_on_develop

#####################
#    DEPLOY DEV     #
#####################

deploy-ui-dev:
  extends: .deploy-ui-dev-int
  stage: deploy-dev
  when: on_success
  <<: *deploy_on_dev
