#############################
#    REUSABLE COMPONENTS    #
#############################

.on_develop: &on_develop
  only:
    - develop
  variables:
    VERSION_BUILD: ${VERSION_SNAPSHOT}

.on_dev: &on_dev
  only:
    - develop
  variables:
    ID_RSA: $ID_RSA_DEV
    SERVER_USER: $SERVER_USER_DEV
    SERVER_IP: $SERVER_IP_DEV
    ENV: "dev"
    VERSION_BUILD: $VERSION_SNAPSHOT

########################
#    SNAPSHOT STEPS    #
########################

snapshot-npm-dev:
  extends: .build
  stage: snapshot
  when: on_success
  <<: *on_develop

snapshot-docker-dev:
  extends: .publish
  stage: snapshot2
  when: on_success
  <<: *on_develop

#####################
#    DEPLOY DEV     #
#####################

deploy-ui-dev:
  extends: .deploy-ui-dev-int
  stage: deploy-dev
  when: on_success
  <<: *on_dev
