version: '3.6'

services:

  host-ui-https-proxy:
    image: registry-pull.viamedis.fr/viamedis/nginx-https-proxy
    container_name: host-ui-https-proxy
    hostname: host-ui-https-proxy
    restart: unless-stopped
    ports:
      - "8030:443"
    environment:
      - PROXY_TARGET=host-ui:8080

  host-ui:
    image: registry-pull.viamedis.fr/common/host-ui:${VERSION_SNAPSHOT}
    container_name: host-ui
    hostname: host-ui
    restart: unless-stopped
#    ports:
#      - "8030:8080"
    environment:
      - REMOTE_LIB_UI=https://10.241.25.10:8038/remoteEntry.js
      - REMOTE_SHARED_LIB_UI=https://10.241.25.10:8039/remoteEntry.js
      - REMOTE_HOSPI=http://10.241.25.10:8032/remoteEntry.js
      - REMOTE_PAYEMENTS=http://10.241.25.10:8033/remoteEntry.js
      - REMOTE_PS=https://10.241.25.10:8034/remoteEntry.js
      - REMOTE_BENEF=http://10.241.25.10:8035/remoteEntry.js
      - APIURL_BENEFICIAIRE=http://10.241.25.10:8007/api/v1
      - APIURL_CONFIGURATIONS=http://10.241.25.10:8015/api/v1
      - APIURL_DOWNLOAD_FACTURE=http://10.241.25.10:8015/api/v1
      - APIURL_DOWNLOAD_SEL_IDB=http://10.241.25.10:8015/api/v1
      - APIURL_ENTITIES=http://10.241.25.10:8031/api/entities
      - APIURL_FACTURES=http://10.241.25.10:8005/api/v1
      - APIURL_FLUX_FACTURES=http://10.241.25.10:8014/api/v1
      - APIURL_INTRAITABLES=http://10.241.25.10:8014/api/v1
      - APIURL_PAIEMENTS=http://10.241.25.10:8003/api/v1
      - APIURL_PS=http://10.241.25.10:8002/api/v1
      - APIURL_SEL_IDB=http://10.241.25.10:8001/api/v1
      - APIURL_FLUX_SEL_IDB=http://10.241.25.10:8001/api/v1
      - APIURL_VIREMENTS=http://10.241.25.10:8003/api/v1
      - APIURL_REFS=http://10.241.25.10:8015/api/v1
      - APIURL_REFERENTIELS=http://10.241.25.10:8004/api/v1
