version: '3.1.9'

services:

  # manual start of proxy SERVICE_DEPLOY = host-ui-https-proxy
  host-ui-https-proxy:
    image: registry-pull.viamedis.fr/viamedis/nginx-https-proxy
    container_name: host-ui-https-proxy
    hostname: host-ui-https-proxy
    restart: unless-stopped
    ports:
      - "8030:443"
    environment:
      - PROXY_TARGET=host-ui:8080

  host-ui:
    image: registry-pull.viamedis.fr/common/host-ui:${VERSION_BUILD}
    container_name: host-ui
    hostname: host-ui
    restart: unless-stopped
    environment:
      #      ************ REMOTE APPs **********************************************************
      - REMOTE_SHARED_LIB_UI=https://10.241.25.10:8039/remoteEntry.js
      - REMOTE_LIB_UI=https://10.241.25.10:8038/remoteEntry.js
      - REMOTE_TPS_UI=https://10.241.25.10:8008/remoteEntry.js
      - REMOTE_HOSPI_UI=https://10.241.25.10:8032/remoteEntry.js
      - REMOTE_INTRAITABLES_UI=https://10.241.25.10:8037/remoteEntry.js
      - REMOTE_PS_UI=https://10.241.25.10:8034/remoteEntry.js
      - REMOTE_PAYEMENTS_UI=https://10.241.25.10:8033/remoteEntry.js
      - REMOTE_BENEF_UI=https://10.241.25.10:8035/remoteEntry.js
      - REMOTE_INDU_UI=https://10.241.25.10:8036/remoteEntry.js
      - REMOTE_AUTH_UI=https://10.241.25.10:8040/remoteEntry.js

      #      ************************ API ***********************************************************
      - APIURL_ROC_SEL_IDB=https://apim-dev-socle.azure-api.net/roc-api/v1
      - APIURL_PS=https://apim-dev-socle.azure-api.net/ps-api/v1
      - APIURL_PAIEMENT_VIREMENT=https://apim-dev-socle.azure-api.net/paiement-api/v1
      - APIURL_REFERENTIELS=https://apim-dev-socle.azure-api.net/referentiel-api/v1
      - APIURL_HOSPI_FACTURES=https://apim-dev-socle.azure-api.net/hospi-facturation-api/v1
      - APIURL_BENEFICIAIRE=https://apim-dev-socle.azure-api.net/droits-beneficiaire-api/v1
      - APIURL_INTEGRATION_FACTURE_INTRITABLES=https://apim-dev-socle.azure-api.net/facturation-integration-api/v1
      - APIURL_AGREGATOR=https://apim-dev-socle.azure-api.net/aggregator-api/v1
      - APIURL_TPS_FACTURES=https://apim-dev-socle.azure-api.net/tps-facturation-api/v1
      - APIURL_TP_AMC_SEL_IDB=https://apim-dev-socle.azure-api.net/tp-amc-api/v1
      - APIURL_INDUS=https://apim-dev-socle.azure-api.net/indu-api/v1
      - APIURL_USER_MANAGEMENT=https://apim-dev-socle.azure-api.net/users-profiles-api/v1

      #      ***************************** AUTH *****************************************************
      - CLIENT_ID=7f53ad13-dd05-4d1e-9239-15210825db3f
      - AUTHORITY=https://integrationviamedisb2c.b2clogin.com/integrationviamedisb2c.onmicrosoft.com/B2C_1_susi_email
      - KNOWN_AUTHORITY=integrationviamedisb2c.b2clogin.com
      - REDIRECT_URI=https://10.241.25.10:8030
      - POST_LOGOUT_REDIRECT_URI=https://10.241.25.10:8030
      - LOGIN_REQUEST_SCOPES=https://integrationviamedisb2c.onmicrosoft.com/f9b81c03-1384-45d9-a8c3-14fc54959a41/hospi_facturation_api.access
      #      ***************************** LEMON LEARNING  *****************************************************
      - LEMON_PROJECT_ID=1f059b51dc8a36d740534339be24b91c
      - LEMON_PROJECT_USER_NAME=Lemon Test
      - LEMON_PROJECT_USER_EMAIL=lemontest@viamedis.fr
      - LEMON_PROFILE=4544
#
