version: '3.5'

services:

  host-ui-dev:
    image: registry-pull.viamedis.fr/common/host-ui:${VERSION_SNAPSHOT}
    container_name: host-ui
    restart: unless-stopped
    ports:
      - "8030:8080"
